export const GET_SESSION_REQ = 'GET_SESSION_REQ';
export const GET_SESSION_OK = 'GET_SESSION_OK';
export const GET_SESSION_ERR = 'GET_SESSION_ERR';
export const CLEAR_SESSION = 'CLEAR_SESSION';

export const TOGGLE_NAV_MENU = 'TOGGLE_NAV_MENU';
export const CHANGE_PAGE_TITLE = 'CHANGE_PAGE_TITLE';