export const CREATE_SESSION_REQ = 'CREATE_SESSION_REQ';
export const CREATE_SESSION_OK = 'CREATE_SESSION_OK';
export const CREATE_SESSION_ERR = 'CREATE_SESSION_ERR';

export const TOGGLE_NAV_MENU = 'TOGGLE_NAV_MENU';
export const CHANGE_PAGE_TITLE = 'CHANGE_PAGE_TITLE';